'use client'
import {useState} from 'react'; import {api} from '../lib/api'; import {useLang} from '../lib/i18n'
function useRun(){const[loading,setLoading]=useState(false); const[err,setErr]=useState(''); return {loading,setLoading,err,setErr}}
export function RunDailyButton(){const s=useRun(); const {lang}=useLang(); return <span>{s.err&&<span className="mr-2 text-sm text-red-400">{s.err}</span>}<button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);s.setErr('');try{await api('/api/runs/daily',{method:'POST',body:JSON.stringify({limit:24,use_four_find:true})}); location.reload()}catch(e:any){s.setErr(e.message);s.setLoading(false)}}}>{s.loading?(lang==='en'?'Running API pipeline...':'API 流水线运行中...'):(lang==='en'?'Run Daily API Pipeline':'运行每日 API 流水线')}</button></span>}
export function AutoTickButton(){const s=useRun(); const {lang}=useLang(); return <span>{s.err&&<span className="mr-2 text-sm text-red-400">{s.err}</span>}<button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);s.setErr('');try{await api('/api/auto/tick',{method:'POST',body:JSON.stringify({force:true})}); location.reload()}catch(e:any){s.setErr(e.message);s.setLoading(false)}}}>{s.loading?(lang==='en'?'Auto running...':'自动运行中...'):(lang==='en'?'Force Auto Tick':'强制自动运行')}</button></span>}
export function DiscoverButton(){const s=useRun(); const {lang}=useLang(); return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api('/api/keywords/discover',{method:'POST',body:JSON.stringify({limit:48})}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>{lang==='en'?'Discover Keywords':'发现关键词'}</button>}
export function SerpButton({id}:{id:number}){const s=useRun(); const {lang}=useLang(); return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api(`/api/keywords/${id}/serp/run`,{method:'POST'}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>{lang==='en'?'Run SERP':'运行 SERP'}</button>}
export function CardButton({id}:{id:number}){const s=useRun(); const {lang}=useLang(); return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api(`/api/cards/generate/${id}`,{method:'POST'}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>{lang==='en'?'Generate Card':'生成卡片'}</button>}
export function Feedback({id}:{id:number}){const labels:any={Action:'行动',Watch:'观察',Reject:'拒绝',Block:'屏蔽'}; return <div className="flex flex-wrap gap-2">{['Action','Watch','Reject','Block'].map(x=><button key={x} title={x} className="rounded bg-slate-800 px-2 py-1 text-xs hover:bg-slate-700" onClick={async()=>{await api(`/api/cards/${id}/feedback`,{method:'POST',body:JSON.stringify({label:x})}); location.reload()}}>{labels[x]} <span className="text-slate-500">{x}</span></button>)}</div>}
export function ExportReportButton(){const[loading,setLoading]=useState(false); const {lang}=useLang(); return <button className="btn" disabled={loading} onClick={async()=>{setLoading(true); const r=await api<any>('/api/reports/export',{method:'POST'}); alert(`${lang==='en'?'Exported':'已导出'}: ${r.path}`); setLoading(false)}}>{lang==='en'?'Export Markdown':'导出 Markdown'}</button>}
export function RepairActionButton({action}:{action:{label:string;action:string;source?:string;safety?:string}}){const[loading,setLoading]=useState(false); return <button className="rounded-lg bg-slate-800 px-2 py-1 text-xs text-slate-200 hover:bg-slate-700 disabled:opacity-50" title={action.safety||''} disabled={loading} onClick={async()=>{if(!confirm(`${action.label}\n\n${action.safety||'仅修改内部设置，可逆。'}`)) return; setLoading(true); try{const r=await api<any>('/api/autopilot/repair',{method:'POST',body:JSON.stringify({action:action.action,source:action.source})}); if(!r.ok) alert(r.error||'repair failed'); location.reload()}catch(e:any){alert(e.message); setLoading(false)}}}>{loading?'处理中...':action.label}</button>}
