'use client'
import {useState} from 'react'; import {api} from '../lib/api'
function useRun(){const[loading,setLoading]=useState(false); const[err,setErr]=useState(''); return {loading,setLoading,err,setErr}}
export function RunDailyButton(){const s=useRun();return <span>{s.err&&<span className="mr-2 text-sm text-red-400">{s.err}</span>}<button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);s.setErr('');try{await api('/api/runs/daily',{method:'POST',body:JSON.stringify({limit:24,use_four_find:true})}); location.reload()}catch(e:any){s.setErr(e.message);s.setLoading(false)}}}>{s.loading?'Running API pipeline...':'Run Daily API Pipeline'}</button></span>}
export function AutoTickButton(){const s=useRun();return <span>{s.err&&<span className="mr-2 text-sm text-red-400">{s.err}</span>}<button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);s.setErr('');try{await api('/api/auto/tick',{method:'POST',body:JSON.stringify({force:true})}); location.reload()}catch(e:any){s.setErr(e.message);s.setLoading(false)}}}>{s.loading?'Auto running...':'Force Auto Tick'}</button></span>}
export function DiscoverButton(){const s=useRun();return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api('/api/keywords/discover',{method:'POST',body:JSON.stringify({limit:48})}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>Discover Keywords</button>}
export function SerpButton({id}:{id:number}){const s=useRun();return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api(`/api/keywords/${id}/serp/run`,{method:'POST'}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>Run SERP</button>}
export function CardButton({id}:{id:number}){const s=useRun();return <button className="btn" disabled={s.loading} onClick={async()=>{s.setLoading(true);try{await api(`/api/cards/generate/${id}`,{method:'POST'}); location.reload()}catch(e:any){alert(e.message);s.setLoading(false)}}}>Generate Card</button>}
export function Feedback({id}:{id:number}){return <div className="flex gap-2">{['Action','Watch','Reject','Block'].map(x=><button key={x} className="rounded bg-slate-800 px-2 py-1 text-xs hover:bg-slate-700" onClick={async()=>{await api(`/api/cards/${id}/feedback`,{method:'POST',body:JSON.stringify({label:x})}); location.reload()}}>{x}</button>)}</div>}
export function ExportReportButton(){const[loading,setLoading]=useState(false);return <button className="btn" disabled={loading} onClick={async()=>{setLoading(true); const r=await api<any>('/api/reports/export',{method:'POST'}); alert(`Exported: ${r.path}`); setLoading(false)}}>Export Markdown</button>}
