'use client'
import {useEffect, useMemo, useRef, useState} from 'react'
import {api} from '../lib/api'

export function ProgressPage({initialProjects, adoptedCards}:{initialProjects:any[]; adoptedCards:any[]}){
 const [projects,setProjects]=useState(initialProjects||[])
 const [selected,setSelected]=useState<any|null>(null)
 const [prd,setPrd]=useState('')
 const [busy,setBusy]=useState(false)
 const [uploadName,setUploadName]=useState('')
 const [uploadSize,setUploadSize]=useState(0)
 const [uploadError,setUploadError]=useState('')
 const [statusFilter,setStatusFilter]=useState('all')
 const [riskFilter,setRiskFilter]=useState('all')
 const [sort,setSort]=useState('score_desc')
 const [q,setQ]=useState('')
 const fileInputRef=useRef<HTMLInputElement|null>(null)
 async function refresh(){setProjects(await api('/api/progress'))}
 async function create(cardId:number){setBusy(true); try{const r:any=await api(`/api/progress/from-card/${cardId}`,{method:'POST'}); setSelected(r); setPrd(r.project.prd_content||''); resetUpload(); await refresh()}finally{setBusy(false)}}
 async function openProject(id:number){const r:any=await api(`/api/progress/${id}`); setSelected(r); setPrd(r.project.prd_content||''); resetUpload()}
 function resetUpload(){setUploadName(''); setUploadSize(0); setUploadError('')}
 async function savePrdAndAnalyze(content:string){if(!selected) return; setBusy(true); try{const saved:any=await api(`/api/progress/${selected.project.id}/prd`,{method:'POST',body:JSON.stringify({content})}); setSelected(saved); setPrd(saved.project.prd_content||content); const analyzed:any=await api(`/api/progress/${saved.project.id}/validate`,{method:'POST'}); setSelected(analyzed); await refresh()}finally{setBusy(false)}}
 async function analyze(){if(!selected) return; setBusy(true); try{const r:any=await api(`/api/progress/${selected.project.id}/validate`,{method:'POST'}); setSelected(r); await refresh()}finally{setBusy(false)}}
 async function uploadPrdFile(file:File|null){
  setUploadError('')
  if(!file) return
  const name=file.name||''
  const lower=name.toLowerCase()
  const isMarkdown=lower.endsWith('.md')||lower.endsWith('.markdown')||file.type==='text/markdown'||file.type==='text/plain'||file.type==='' 
  if(!isMarkdown){setUploadError('只支持上传 .md / .markdown Markdown 文档。'); return}
  const text=await file.text()
  if(!text.trim()){setUploadError('Markdown 文档为空，无法保存。'); return}
  setPrd(text); setUploadName(name); setUploadSize(file.size)
  await savePrdAndAnalyze(text)
 }
 useEffect(()=>{const id=new URLSearchParams(location.search).get('project'); if(id) openProject(Number(id))},[])
 const projectByCard=new Map(projects.map((p:any)=>[p.representative_card_id,p]))
 const rows=useMemo(()=>{
  const merged=adoptedCards.map((c:any)=>{
   const p=projectByCard.get(c.id) as any
   const biz=(c.evidence_json||[]).find((e:any)=>e.type==='business')||{}
   return {card:c, project:p, id:p?`p-${p.id}`:`c-${c.id}`, title:c.opportunity_group?.canonical_keyword||c.title, source:c.source_keyword||c.keyword||'', status:p?.status||'not_started', risk:p?.risk_level||'unknown', originalScore:Number(c.score||0), productScore:Number(p?.feasibility_score||c.score||0), delta:Number(p?.score_delta||0), monetization:biz.business_type||c.monetization_type||'', mvp:biz.commercial_mvp||c.mvp_plan||'', prdReady:!!p?.prd_version, next:p?.next_action||'上传 PRD.md 后开始产品分析。'}
  })
  return merged.filter((r:any)=>statusFilter==='all'||r.status===statusFilter||(!r.project&&statusFilter==='not_started')).filter((r:any)=>riskFilter==='all'||r.risk===riskFilter).filter((r:any)=>!q.trim()||`${r.title} ${r.monetization} ${r.mvp}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>sort==='score_asc'?a.productScore-b.productScore:sort==='delta_desc'?b.delta-a.delta:sort==='delta_asc'?a.delta-b.delta:sort==='risk'?riskRank(b.risk)-riskRank(a.risk):b.productScore-a.productScore)
 },[adoptedCards,projects,statusFilter,riskFilter,sort,q])
 const statuses=Array.from(new Set(['not_started',...projects.map((p:any)=>p.status)]))
 return <div className="space-y-6">
  <section className="rounded-3xl border border-purple-500/20 bg-gradient-to-br from-purple-950/60 via-slate-950 to-slate-950 p-7 shadow-2xl"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-purple-300">Opportunity Progress</p><h1 className="mt-3 text-4xl font-black text-white">机会推进 / 产品分析</h1><p className="mt-3 max-w-4xl text-slate-300">一个表格管理所有已采纳机会。上传 PRD 后，系统先分析 PRD 合理性，再围绕目标用户、商业逻辑、付费路径、竞争对手、获客方式抓取证据并重新评分。</p></section>
  <section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">已采纳机会推进表</h2><p className="mt-1 text-sm text-slate-400">筛选、排序、打开明细；不要左右两个列表。</p></div><div className="flex flex-wrap gap-2 text-sm"><span className="badge">{rows.length}/{adoptedCards.length} 条</span><span className="badge">projects {projects.length}</span></div></div>
   <div className="mt-4 grid gap-3 rounded-2xl border border-slate-800 bg-slate-950 p-3 md:grid-cols-[1fr_150px_150px_150px]"><input className="input" placeholder="搜索机会 / 变现 / MVP" value={q} onChange={e=>setQ(e.target.value)}/><Select value={statusFilter} setValue={setStatusFilter} options={[['all','全部状态'],...statuses.map(x=>[x,statusLabel(x)])]}/><Select value={riskFilter} setValue={setRiskFilter} options={[['all','全部风险'],['low','low'],['medium','medium'],['high','high'],['critical','critical'],['unknown','unknown']]}/><Select value={sort} setValue={setSort} options={[['score_desc','产品评分 ↓'],['score_asc','产品评分 ↑'],['delta_desc','评分变化 ↓'],['delta_asc','评分变化 ↑'],['risk','风险优先']]}/></div>
   <div className="mt-4 overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[1180px] table-fixed text-left text-sm"><colgroup><col className="w-[320px]"/><col className="w-[128px]"/><col className="w-[76px]"/><col className="w-[86px]"/><col className="w-[66px]"/><col className="w-[88px]"/><col className="w-[86px]"/><col className="w-[250px]"/><col className="w-[92px]"/></colgroup><thead className="bg-slate-900/70 text-xs text-slate-500"><tr><th className="px-4 py-3">机会 / 原信息</th><th className="px-3 py-3">产品分析状态</th><th className="px-3 py-3">原评分</th><th className="px-3 py-3">产品评分</th><th className="px-3 py-3">Δ</th><th className="px-3 py-3">风险</th><th className="px-3 py-3">PRD</th><th className="px-3 py-3">下一步</th><th className="px-3 py-3">操作</th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id} className="border-t border-slate-800 align-top hover:bg-slate-900/40"><td className="px-4 py-4"><b className="block truncate text-blue-200" title={r.title}>{r.title}</b><div className="mt-1 flex min-w-0 flex-wrap gap-1"><span className="max-w-[280px] truncate rounded bg-slate-900 px-2 py-0.5 text-[11px] text-slate-400" title={r.monetization||'-'}>{r.monetization||'未标注变现'}</span></div><p className="mt-2 overflow-hidden break-words text-xs leading-5 text-slate-500" style={{display:'-webkit-box',WebkitLineClamp:2,WebkitBoxOrient:'vertical'}} title={r.mvp||''}>{r.mvp||'暂无 MVP 摘要'}</p></td><td className="px-3 py-4"><span className="badge whitespace-nowrap">{statusLabel(r.status)}</span></td><td className="px-3 py-4 text-slate-300">{Math.round(r.originalScore)}</td><td className="px-3 py-4 text-purple-300">{Math.round(r.productScore)}</td><td className={`px-3 py-4 ${r.delta>0?'text-emerald-300':r.delta<0?'text-rose-300':'text-slate-400'}`}>{r.delta>0?'+':''}{r.delta}</td><td className="px-3 py-4"><span className={riskClass(r.risk)}>{r.risk}</span></td><td className="px-3 py-4">{r.prdReady?<span className="whitespace-nowrap text-emerald-300">已上传</span>:<span className="whitespace-nowrap text-slate-500">未上传</span>}</td><td className="px-3 py-4"><p className="overflow-hidden break-words text-xs leading-5 text-slate-400" style={{display:'-webkit-box',WebkitLineClamp:2,WebkitBoxOrient:'vertical'}} title={r.next}>{r.next}</p></td><td className="px-3 py-4"><button disabled={busy} className={r.project?'btn-secondary':'btn'} onClick={()=>r.project?openProject(r.project.id):create(r.card.id)}>{r.project?'明细':'开始'}</button></td></tr>):<tr><td colSpan={9} className="px-4 py-8 text-center text-slate-500">暂无符合条件的采纳机会。</td></tr>}</tbody></table></div>
  </section>
  {selected&&<ProgressDrawer selected={selected} busy={busy} prd={prd} uploadName={uploadName} uploadSize={uploadSize} uploadError={uploadError} fileInputRef={fileInputRef} onClose={()=>setSelected(null)} onUpload={uploadPrdFile} onAnalyze={analyze}/>} 
 </div>
}

function ProgressDrawer({selected,busy,prd,uploadName,uploadSize,uploadError,fileInputRef,onClose,onUpload,onAnalyze}:any){
 const opp=selected.project.opportunity||{}
 const biz=opp.business||{}
 const latest=selected.runs?.[0]
 const analysis=latest?.summary?.analysis||{}
 return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-black/60" onClick={onClose}/><aside className="absolute right-0 top-0 h-full w-full max-w-7xl overflow-y-auto border-l border-slate-800 bg-slate-950 p-5 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-3"><div><div className="text-xs uppercase tracking-[0.25em] text-purple-300">Product Analysis</div><h2 className="mt-1 text-2xl font-bold text-white">{selected.project.canonical_keyword}</h2><p className="mt-1 text-sm text-slate-400">原评分 {Math.round(selected.project.original_score||0)} → 产品评分 {Math.round(selected.project.feasibility_score||0)} · Δ {selected.project.score_delta>0?'+':''}{selected.project.score_delta} · 风险 {selected.project.risk_level}</p></div><button className="btn-secondary" onClick={onClose}>关闭</button></div>
  <section className="mb-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="grid gap-4 lg:grid-cols-[1fr_auto]"><div><h3 className="font-bold text-white">PRD 文档</h3><p className="mt-1 text-sm text-slate-400">上传后自动开始产品分析：PRD 合理性 → 产品方案 → 用户/商业/付费/竞品/获客 → 证据计划 → 重新评分。</p><div className="mt-2 text-xs text-slate-500">保存路径：{selected.project.prd_path||'上传后生成 prds/<slug>/PRD.md'} · 当前长度 {(selected.project.prd_content||prd||'').trim().length} 字符</div>{uploadName&&<p className="mt-2 rounded-xl border border-emerald-500/20 bg-emerald-950/30 px-3 py-2 text-xs text-emerald-200">已上传并分析：{uploadName} · {formatBytes(uploadSize)}</p>}{uploadError&&<p className="mt-2 rounded-xl border border-amber-500/20 bg-amber-950/30 px-3 py-2 text-xs text-amber-200">{uploadError}</p>}{busy&&<p className="mt-2 rounded-xl border border-blue-500/20 bg-blue-950/30 px-3 py-2 text-xs text-blue-200">正在进行产品分析和证据抓取...</p>}</div><div className="flex flex-wrap items-center gap-2"><input ref={fileInputRef} type="file" accept=".md,.markdown,text/markdown,text/plain" className="hidden" onChange={(e:any)=>onUpload(e.target.files?.[0]||null)}/><button className="btn" disabled={busy} onClick={()=>fileInputRef.current?.click()}>{selected.project.prd_content?'重新上传并分析':'上传 PRD 并分析'}</button><button className="btn-secondary" disabled={busy||!selected.project.prd_content} onClick={onAnalyze}>重新分析</button></div></div></section>
  <div className="grid gap-4 xl:grid-cols-2"><section className="space-y-4"><Info title="原采纳机会" text={`${opp.title||selected.project.canonical_keyword}\n关键词：${opp.keyword||'-'}\n变现：${biz.business_type||opp.monetization_type||'-'}\n原判断：${biz.verdict_reason||biz.go_no_go||'-'}`}/><ScoreCards opp={opp}/><Info title="PRD 合理性" text={fmtObj(analysis.prd_reasonableness)}/><Info title="产品方案" text={fmtObj(analysis.product_plan)}/><Info title="商业逻辑" text={fmtObj(analysis.commercial_logic)}/><Info title="付费路径" text={fmtObj(analysis.payment_path)}/><Info title="总体突破口 / 差异化" text={analysis.wedge}/><Info title="下一步" text={selected.project.next_action}/></section><section className="space-y-4"><TargetUserTable rows={arr(analysis.target_users)}/><CompetitorTable rows={arr(analysis.competitor_table)} fallback={selected.competitors}/><AcquisitionTable rows={arr(analysis.acquisition_channels)}/><EvidencePlanTable rows={arr(analysis.evidence_plan)}/><List title="PRD 待补强" rows={arr(analysis.prd_gaps)}/><List title="分析记录" rows={selected.runs.map((r:any)=>`#${r.id} ${r.kind} ${r.status} · ${r.summary?.old_score??'-'} → ${r.summary?.new_score??'-'} · competitors=${r.summary?.competitors||0}`)}/></section></div></aside></div>
}
function ScoreCards({opp}:any){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">原机会评分</h3><div className="mt-3 grid grid-cols-2 gap-2 text-xs md:grid-cols-3"><Metric label="总分" value={opp.score}/><Metric label="需求" value={opp.demand_score}/><Metric label="SERP" value={opp.serp_gap_score}/><Metric label="竞品弱点" value={opp.competitor_weakness_score}/><Metric label="商业" value={opp.commercial_score}/><Metric label="变现" value={opp.monetization_score}/></div></div>}
function TargetUserTable({rows}:any){return <Table title="目标用户 / 需求入口" cols={['用户分群','痛点','证据/入口','置信']} rows={rows.map((r:any)=>[r.segment,r.pain,r.evidence,r.confidence])}/>}
function CompetitorTable({rows,fallback}:any){const data=rows.length?rows:fallback.map((c:any)=>({name:c.name||c.domain,domain:c.domain,positioning:c.notes,pricing:c.pricing_url,strength:'待分析',weakness:'待分析',similarity:'-',threat:'-',wedge:'待补证'})); return <Table title="竞争对手多维分析" cols={['竞品','域名','定位','定价信号','强项','弱项','相似度','威胁','突破口']} rows={data.map((r:any)=>[r.name,r.domain,r.positioning,r.pricing,r.strength,r.weakness,r.similarity,r.threat,r.wedge])}/>}
function AcquisitionTable({rows}:any){return <Table title="获客方式" cols={['渠道','入口','证据','成本','置信']} rows={rows.map((r:any)=>[r.channel,r.entry,r.evidence,r.cost,r.confidence])}/>}
function EvidencePlanTable({rows}:any){return <Table title="证据抓取 / 验证计划" cols={['验证点','方法','成功信号']} rows={rows.map((r:any)=>[r.area,r.method,r.success_signal])}/>}
function Table({title,cols,rows}:{title:string;cols:string[];rows:any[][]}){return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3><div className="mt-3 overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr>{cols.map(c=><th key={c} className="px-3 py-2">{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t border-slate-800 align-top">{r.map((x,j)=><td key={j} className="whitespace-pre-wrap px-3 py-2 text-slate-300">{x||'-'}</td>)}</tr>):<tr><td colSpan={cols.length} className="px-3 py-4 text-center text-slate-500">暂无，需要继续抓取证据。</td></tr>}</tbody></table></div></section>}
function Select({value,setValue,options}:any){return <select className="input" value={value} onChange={e=>setValue(e.target.value)}>{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>}
function arr(x:any){return Array.isArray(x)?x.filter(Boolean):x?[x]:[]}
function fmtObj(x:any){if(!x) return ''; if(typeof x==='string') return x; return Object.entries(x).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join('；'):v}`).join('\n')}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-slate-950/80 p-2"><div className="text-slate-500">{label}</div><b className="text-slate-100">{value??'-'}</b></div>}
function Info({title,text}:{title:string;text?:string}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{text||'暂无'}</p></div>}
function List({title,rows}:{title:string;rows:any[]}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3>{rows.length?<ul className="mt-2 space-y-2 text-sm text-slate-300">{rows.map((x,i)=><li key={i} className="whitespace-pre-wrap rounded-xl bg-slate-950 p-2">{typeof x==='string'?x:fmtObj(x)}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">暂无。</p>}</div>}
function statusLabel(x:string){const m:any={not_started:'未开始',needs_prd:'待上传 PRD',prd_ready:'待产品分析',analysis_continue:'继续推进',analysis_need_evidence:'需补证',analysis_adjust_prd:'需改 PRD',analysis_pause:'暂停'}; return m[x]||x}
function riskRank(x:string){return {critical:4,high:3,medium:2,low:1,unknown:0}[x as string]||0}
function riskClass(x:string){return `rounded-lg px-2 py-1 text-xs ${x==='critical'||x==='high'?'bg-rose-500/10 text-rose-200':x==='medium'?'bg-amber-500/10 text-amber-200':x==='low'?'bg-emerald-500/10 text-emerald-200':'bg-slate-800 text-slate-300'}`}
function formatBytes(size:number){if(!size) return '0 B'; const units=['B','KB','MB','GB']; let n=size; let i=0; while(n>=1024&&i<units.length-1){n/=1024; i++} return `${n.toFixed(n>=10||i===0?0:1)} ${units[i]}`}
