'use client'
import {useEffect, useMemo, useRef, useState} from 'react'
import {api} from '../lib/api'

export function ProgressPage({initialProjects, adoptedCards}:{initialProjects:any[]; adoptedCards:any[]}){
 const [projects,setProjects]=useState(initialProjects||[])
 const [selected,setSelected]=useState<any|null>(null)
 const [prd,setPrd]=useState('')
 const [busy,setBusy]=useState(false)
 const [uploadName,setUploadName]=useState('')
 const [uploadSize,setUploadSize]=useState(0)
 const [uploadError,setUploadError]=useState('')
 const [statusFilter,setStatusFilter]=useState('all')
 const [riskFilter,setRiskFilter]=useState('all')
 const [sort,setSort]=useState('score_desc')
 const [q,setQ]=useState('')
 const fileInputRef=useRef<HTMLInputElement|null>(null)
 async function refresh(){setProjects(await api('/api/progress'))}
 async function create(cardId:number){setBusy(true); try{const r:any=await api(`/api/progress/from-card/${cardId}`,{method:'POST'}); setSelected(r); setPrd(r.project.prd_content||''); resetUpload(); await refresh()}finally{setBusy(false)}}
 async function openProject(id:number){const r:any=await api(`/api/progress/${id}`); setSelected(r); setPrd(r.project.prd_content||''); resetUpload()}
 function resetUpload(){setUploadName(''); setUploadSize(0); setUploadError('')}
 async function savePrdAndAnalyze(content:string){if(!selected) return; setBusy(true); try{const saved:any=await api(`/api/progress/${selected.project.id}/prd`,{method:'POST',body:JSON.stringify({content})}); setSelected(saved); setPrd(saved.project.prd_content||content); const analyzed:any=await api(`/api/progress/${saved.project.id}/validate`,{method:'POST'}); setSelected(analyzed); await refresh()}finally{setBusy(false)}}
 async function analyze(){if(!selected) return; setBusy(true); try{const r:any=await api(`/api/progress/${selected.project.id}/validate`,{method:'POST'}); setSelected(r); await refresh()}finally{setBusy(false)}}
 async function uploadPrdFile(file:File|null){
  setUploadError('')
  if(!file) return
  const name=file.name||''
  const lower=name.toLowerCase()
  const isMarkdown=lower.endsWith('.md')||lower.endsWith('.markdown')||file.type==='text/markdown'||file.type==='text/plain'||file.type==='' 
  if(!isMarkdown){setUploadError('只支持上传 .md / .markdown Markdown 文档。'); return}
  const text=await file.text()
  if(!text.trim()){setUploadError('Markdown 文档为空，无法保存。'); return}
  setPrd(text); setUploadName(name); setUploadSize(file.size)
  await savePrdAndAnalyze(text)
 }
 useEffect(()=>{const id=new URLSearchParams(location.search).get('project'); if(id) openProject(Number(id))},[])
 const projectByCard=new Map(projects.map((p:any)=>[p.representative_card_id,p]))
 const rows=useMemo(()=>{
  const merged=adoptedCards.map((c:any)=>{
   const p=projectByCard.get(c.id) as any
   const biz=(c.evidence_json||[]).find((e:any)=>e.type==='business')||{}
   return {card:c, project:p, id:p?`p-${p.id}`:`c-${c.id}`, title:c.opportunity_group?.canonical_keyword||c.title, source:c.source_keyword||c.keyword||'', status:p?.status||'not_started', risk:p?.risk_level||'unknown', originalScore:Number(c.score||0), productScore:Number(p?.feasibility_score||c.score||0), delta:Number(p?.score_delta||0), monetization:biz.business_type||c.monetization_type||'', mvp:biz.commercial_mvp||c.mvp_plan||'', prdReady:!!p?.prd_version, next:p?.next_action||'上传 PRD.md 后开始产品分析。'}
  })
  return merged.filter((r:any)=>statusFilter==='all'||r.status===statusFilter||(!r.project&&statusFilter==='not_started')).filter((r:any)=>riskFilter==='all'||r.risk===riskFilter).filter((r:any)=>!q.trim()||`${r.title} ${r.monetization} ${r.mvp}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>sort==='score_asc'?a.productScore-b.productScore:sort==='delta_desc'?b.delta-a.delta:sort==='delta_asc'?a.delta-b.delta:sort==='risk'?riskRank(b.risk)-riskRank(a.risk):b.productScore-a.productScore)
 },[adoptedCards,projects,statusFilter,riskFilter,sort,q])
 const statuses=Array.from(new Set(['not_started',...projects.map((p:any)=>p.status)]))
 return <div className="space-y-6">
  <section className="rounded-3xl border border-purple-500/20 bg-gradient-to-br from-purple-950/60 via-slate-950 to-slate-950 p-7 shadow-2xl"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-purple-300">Opportunity Progress</p><h1 className="mt-3 text-4xl font-black text-white">机会推进 / 产品分析</h1><p className="mt-3 max-w-4xl text-slate-300">一个表格管理所有已采纳机会。上传 PRD 后，系统先分析 PRD 合理性，再围绕目标用户、商业逻辑、付费路径、竞争对手、获客方式抓取证据并重新评分。</p></section>
  <section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">已采纳机会推进表</h2><p className="mt-1 text-sm text-slate-400">筛选、排序、打开明细；不要左右两个列表。</p></div><div className="flex flex-wrap gap-2 text-sm"><span className="badge">{rows.length}/{adoptedCards.length} 条</span><span className="badge">projects {projects.length}</span></div></div>
   <div className="mt-4 grid gap-3 rounded-2xl border border-slate-800 bg-slate-950 p-3 md:grid-cols-[1fr_150px_150px_150px]"><input className="input" placeholder="搜索机会 / 变现 / MVP" value={q} onChange={e=>setQ(e.target.value)}/><Select value={statusFilter} setValue={setStatusFilter} options={[['all','全部状态'],...statuses.map(x=>[x,statusLabel(x)])]}/><Select value={riskFilter} setValue={setRiskFilter} options={[['all','全部风险'],['low','low'],['medium','medium'],['high','high'],['critical','critical'],['unknown','unknown']]}/><Select value={sort} setValue={setSort} options={[['score_desc','产品评分 ↓'],['score_asc','产品评分 ↑'],['delta_desc','评分变化 ↓'],['delta_asc','评分变化 ↑'],['risk','风险优先']]}/></div>
   <div className="mt-4 overflow-hidden rounded-2xl border border-slate-800"><table className="w-full table-fixed text-left text-sm"><colgroup><col className="w-[30%]"/><col className="w-[12%]"/><col className="w-[6%]"/><col className="w-[7%]"/><col className="w-[6%]"/><col className="w-[8%]"/><col className="w-[7%]"/><col className="w-[24%]"/></colgroup><thead className="bg-slate-900/70 text-xs text-slate-500"><tr><th className="px-4 py-3">机会 / 原信息</th><th className="px-2 py-3">状态</th><th className="px-2 py-3">原分</th><th className="px-2 py-3">产品分</th><th className="px-2 py-3">变化</th><th className="px-2 py-3">风险</th><th className="px-2 py-3">PRD</th><th className="px-3 py-3">下一步</th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id} role="button" tabIndex={0} onClick={()=>r.project?openProject(r.project.id):create(r.card.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault(); r.project?openProject(r.project.id):create(r.card.id)}}} className="cursor-pointer border-t border-slate-800 align-top transition hover:bg-slate-900/60 focus:outline-none focus:ring-2 focus:ring-blue-500/50"><td className="px-4 py-4"><b className="block truncate text-blue-200" title={r.title}>{r.title}</b><div className="mt-1 flex min-w-0 flex-wrap gap-1"><span className="max-w-full truncate rounded bg-slate-900 px-2 py-0.5 text-[11px] text-slate-400" title={r.monetization||'-'}>{r.monetization||'未标注变现'}</span></div><p className="mt-2 overflow-hidden break-words text-xs leading-5 text-slate-500" style={{display:'-webkit-box',WebkitLineClamp:2,WebkitBoxOrient:'vertical'}} title={r.mvp||''}>{r.mvp||'暂无 MVP 摘要'}</p></td><td className="px-2 py-4"><span className="inline-block max-w-full truncate rounded border border-slate-700 bg-slate-900 px-2 py-1 text-[11px] text-slate-300" title={statusLabel(r.status)}>{statusLabel(r.status)}</span></td><td className="px-2 py-4 text-slate-300">{Math.round(r.originalScore)}</td><td className="px-2 py-4 text-purple-300">{Math.round(r.productScore)}</td><td className={`px-2 py-4 ${r.delta>0?'text-emerald-300':r.delta<0?'text-rose-300':'text-slate-400'}`}>{r.delta>0?'+':''}{r.delta}</td><td className="px-2 py-4"><span className={riskClass(r.risk)}>{r.risk}</span></td><td className="px-2 py-4">{r.prdReady?<span className="text-emerald-300">已传</span>:<span className="text-slate-500">未传</span>}</td><td className="px-3 py-4"><p className="whitespace-normal break-words text-xs leading-5 text-slate-400" title={r.next}>{r.next}</p></td></tr>):<tr><td colSpan={8} className="px-4 py-8 text-center text-slate-500">暂无符合条件的采纳机会。</td></tr>}</tbody></table></div>
  </section>
  {selected&&<ProgressDrawer selected={selected} busy={busy} prd={prd} uploadName={uploadName} uploadSize={uploadSize} uploadError={uploadError} fileInputRef={fileInputRef} onClose={()=>setSelected(null)} onUpload={uploadPrdFile} onAnalyze={analyze}/>} 
 </div>
}

function ProgressDrawer({selected,busy,prd,uploadName,uploadSize,uploadError,fileInputRef,onClose,onUpload,onAnalyze}:any){
 const opp=selected.project.opportunity||{}
 const biz=opp.business||{}
 const latest=selected.runs?.[0]
 const analysis=latest?.summary?.analysis||{}
 const decision=analysis.decision_summary||analysis.executive_summary||{}
 const scoreReason=analysis.score_change_reason||decision.score_change_reason||''
 return <div className="fixed inset-0 z-50"><button className="absolute inset-0 bg-black/60" onClick={onClose}/><aside className="absolute right-0 top-0 h-full w-full max-w-7xl overflow-y-auto overflow-x-hidden border-l border-slate-800 bg-slate-950 p-5 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-3"><div><div className="text-xs uppercase tracking-[0.25em] text-purple-300">Product Decision Workspace</div><h2 className="mt-1 text-2xl font-bold text-white">{selected.project.canonical_keyword}</h2><p className="mt-1 text-sm text-slate-400">先看结论，再看依据；原机会只作为基线参考。</p></div><button className="btn-secondary" onClick={onClose}>关闭</button></div>
  <DecisionHero selected={selected} analysis={analysis}/>
  <section className="mt-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="grid gap-4 lg:grid-cols-[1fr_auto]"><div><h3 className="font-bold text-white">PRD 文档</h3><p className="mt-1 text-sm text-slate-400">上传后进入产品分析：先判断 PRD 合理性，再验证用户、商业、付费、竞品和获客路径。</p><div className="mt-2 text-xs text-slate-500">保存路径：{selected.project.prd_path||'上传后生成 prds/<slug>/PRD.md'} · 当前长度 {(selected.project.prd_content||prd||'').trim().length} 字符</div>{uploadName&&<p className="mt-2 rounded-xl border border-emerald-500/20 bg-emerald-950/30 px-3 py-2 text-xs text-emerald-200">已上传并分析：{uploadName} · {formatBytes(uploadSize)}</p>}{uploadError&&<p className="mt-2 rounded-xl border border-amber-500/20 bg-amber-950/30 px-3 py-2 text-xs text-amber-200">{uploadError}</p>}{busy&&<p className="mt-2 rounded-xl border border-blue-500/20 bg-blue-950/30 px-3 py-2 text-xs text-blue-200">正在进行产品分析和证据抓取...</p>}</div><div className="flex flex-wrap items-center gap-2"><input ref={fileInputRef} type="file" accept=".md,.markdown,text/markdown,text/plain" className="hidden" onChange={(e:any)=>onUpload(e.target.files?.[0]||null)}/><button className="btn" disabled={busy} onClick={()=>fileInputRef.current?.click()}>{selected.project.prd_content?'重新上传并分析':'上传 PRD 并分析'}</button><button className="btn-secondary" disabled={busy||!selected.project.prd_content} onClick={onAnalyze}>重新分析</button></div></div></section>
  <div className="mt-4 space-y-4">
   <OriginalBaseline opp={opp} biz={biz}/>
   <SectionTitle step="01" title="总体产品分析" desc="先给出总判断：值不值得推进、为什么变分、最大机会和最大风险。"/>
   <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]"><Info title="总体判断" text={fmtObj(decision)||analysis.notification||selected.project.next_action}/><Info title="评分变化原因" text={scoreReason}/></div>
   <div className="grid gap-4 xl:grid-cols-2"><Info title="最大机会" text={decision.biggest_opportunity||analysis.biggest_opportunity}/><Info title="最大风险" text={decision.biggest_risk||analysis.biggest_risk}/></div>
   <SectionTitle step="02" title="PRD 合理性" desc="先判断 PRD 是否继承原机会、是否收窄到可验证 MVP、是否能导向付费。"/>
   <Info title="PRD 合理性分析" text={fmtObj(analysis.prd_reasonableness)}/>
   <Info title="产品方案" text={fmtObj(analysis.product_plan)}/>
   <SectionTitle step="03" title="目标用户与需求入口" desc="看谁真的痛、在哪里能触达、证据强不强。"/>
   <TargetUserTable rows={arr(analysis.target_users)}/>
   <SectionTitle step="04" title="商业逻辑与付费路径" desc="判断价值创造、预算归属、付费触发和首单路径。"/>
   <div className="grid gap-4 xl:grid-cols-2"><Info title="商业逻辑" text={fmtObj(analysis.commercial_logic)}/><Info title="付费路径" text={fmtObj(analysis.payment_path)}/></div>
   <SectionTitle step="05" title="竞争对手" desc="表格只保留关键判断；点击公司名查看强弱、正面竞争、护城河和切入方式。"/>
   <CompetitorTable rows={arr(analysis.competitor_table)} fallback={selected.competitors}/>
   <SectionTitle step="06" title="获客方式" desc="判断第一批用户从哪里来、成本是否可接受、是否能验证。"/>
   <AcquisitionTable rows={arr(analysis.acquisition_channels)}/>
   <SectionTitle step="07" title="证据验证计划" desc="下一步不是做 MVP，而是按假设继续抓证据和做最小验证。"/>
   <EvidencePlanTable rows={arr(analysis.evidence_plan)}/>
   <div className="grid gap-4 xl:grid-cols-2"><List title="PRD 待补强" rows={arr(analysis.prd_gaps)}/><Collapsible title="系统记录 / 原始分析数据"><List title="分析记录" rows={selected.runs.map((r:any)=>`#${r.id} ${r.kind} ${r.status} · ${r.summary?.old_score??'-'} → ${r.summary?.new_score??'-'} · competitors=${r.summary?.competitors||0}`)}/><Info title="LLM 原始输出" text={JSON.stringify(analysis,null,2)}/></Collapsible></div>
  </div></aside></div>
}

function DecisionHero({selected,analysis}:any){const status=statusLabel(selected.project.status); const delta=Number(selected.project.score_delta||0); return <section className="rounded-3xl border border-purple-500/20 bg-gradient-to-br from-purple-950/70 via-slate-900 to-slate-950 p-5"><div className="grid gap-4 lg:grid-cols-[1fr_320px]"><div><div className="text-xs uppercase tracking-[0.25em] text-purple-300">Decision Summary</div><h3 className="mt-2 text-2xl font-black text-white">{status}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">{analysis.notification||selected.project.next_action||'上传 PRD 后生成产品分析结论。'}</p></div><div className="grid grid-cols-2 gap-2 text-xs"><Metric label="原分" value={Math.round(selected.project.original_score||0)}/><Metric label="产品分" value={Math.round(selected.project.feasibility_score||0)}/><Metric label="变化" value={`${delta>0?'+':''}${delta}`}/><Metric label="风险" value={selected.project.risk_level}/></div></div></section>}
function OriginalBaseline({opp,biz}:any){return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-white">原始机会基线 / 参考</h3><p className="mt-1 text-sm text-slate-400">默认只保留对比摘要；完整商业分析和全部证据点击后展开。</p></div><span className="badge">参考信息</span></div><div className="mt-3 grid gap-3 md:grid-cols-[1.2fr_0.8fr]"><Info title="机会摘要" text={`${opp.title||'-'}\n关键词：${opp.keyword||'-'}\n原判断：${biz.verdict_reason||biz.go_no_go||opp.verdict||'-'}\n原 MVP：${biz.commercial_mvp||opp.mvp_plan||'-'}`}/><ScoreCards opp={opp} risks={opp.risks}/></div><details className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/60"><summary className="cursor-pointer list-none px-4 py-3"><div className="flex items-center justify-between gap-3"><div><b className="text-sm text-slate-100">展开原机会完整证据</b><p className="mt-1 text-xs text-slate-500">包含原商业分析和证据链摘要，只用于追溯，不作为当前产品分析主视觉。</p></div><span className="rounded-lg border border-slate-700 px-2 py-1 text-xs text-slate-400">展开</span></div></summary><div className="space-y-4 border-t border-slate-800 p-4"><OriginalBusinessAnalysis biz={biz} opp={opp}/><EvidenceSummary evidence={opp.evidence||[]}/></div></details></section>}
function OriginalBusinessAnalysis({biz,opp}:any){return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">原商业分析</h3><p className="mt-1 text-xs text-slate-500">按主题拆分，避免展示原始 block 和大段文字。</p><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><MiniBlock title="判断" text={biz.verdict_reason||biz.go_no_go||opp.verdict}/><MiniBlock title="目标用户" text={biz.icp}/><MiniBlock title="核心痛点" text={biz.pain}/><MiniBlock title="付费触发" text={biz.pay_trigger}/><MiniBlock title="切入点" text={biz.wedge}/><MiniBlock title="原 MVP" text={biz.commercial_mvp||opp.mvp_plan}/><MiniBlock title="收入路径" text={biz.revenue_path}/><MiniBlock title="定价测试" text={biz.pricing}/><MiniBlock title="获客方式" text={biz.gtm}/><MiniBlock title="第一笔钱测试" text={biz.first_sale_test}/><MiniBlock title="关键假设" text={biz.key_assumption}/><MiniBlock title="主要风险" text={biz.risk}/></div>{arr(biz.missing_evidence).length>0&&<div className="mt-4"><List title="待补证据" rows={arr(biz.missing_evidence)}/></div>}</section>}
function MiniBlock({title,text}:any){return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-3"><div className="text-xs font-semibold text-slate-500">{title}</div><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-5 text-slate-200">{text||'暂无'}</p></div>}
function EvidenceSummary({evidence}:any){const rows=arr(evidence).filter((e:any)=>e&&e.type!=='business').slice(0,12); return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">证据链摘要</h3><p className="mt-1 text-xs text-slate-500">只展示用户可读摘要，不展示原始 JSON。</p>{rows.length?<div className="mt-3 space-y-2">{rows.map((e:any,i:number)=><div key={i} className="rounded-xl bg-slate-950 p-3 text-sm text-slate-300"><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-slate-800 px-2 py-0.5 text-[11px] text-slate-400">{e.type||'evidence'}</span>{e.source&&<span className="text-xs text-slate-500">{e.source}</span>}</div><div className="mt-1 break-words font-medium text-slate-200">{e.title||e.keyword||e.query||e.domain||e.url||'证据记录'}</div>{(e.summary||e.snippet||e.notes||e.reason)&&<p className="mt-1 whitespace-pre-wrap break-words text-xs leading-5 text-slate-400">{e.summary||e.snippet||e.notes||e.reason}</p>}{e.url&&<a className="mt-1 block break-words text-xs text-blue-300 hover:text-blue-200" href={e.url} target="_blank" rel="noreferrer">{e.url}</a>}</div>)}</div>:<p className="mt-3 text-sm text-slate-500">暂无可读证据摘要。</p>}</section>}
function SectionTitle({step,title,desc}:any){return <div className="pt-2"><div className="flex items-center gap-3"><span className="rounded-full border border-purple-500/30 bg-purple-950/50 px-3 py-1 text-xs font-bold text-purple-200">{step}</span><h3 className="text-lg font-bold text-white">{title}</h3></div>{desc&&<p className="mt-1 text-sm text-slate-500">{desc}</p>}</div>}
function Collapsible({title,children}:any){return <details className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><summary className="cursor-pointer list-none font-bold text-white">{title}</summary><div className="mt-3 space-y-3">{children}</div></details>}
function ScoreCards({opp,risks}:any){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">原机会评分</h3><div className="mt-3 grid grid-cols-2 gap-2 text-xs md:grid-cols-3"><Metric label="总分" value={opp.score}/><Metric label="需求" value={opp.demand_score}/><Metric label="SERP" value={opp.serp_gap_score}/><Metric label="竞品弱点" value={opp.competitor_weakness_score}/><Metric label="商业" value={opp.commercial_score}/><Metric label="变现" value={opp.monetization_score}/></div>{arr(risks).length>0&&<div className="mt-3 rounded-xl border border-amber-500/20 bg-amber-950/20 p-3"><div className="text-xs font-semibold text-amber-200">原始风险</div><ul className="mt-2 space-y-1 text-xs leading-5 text-amber-100/80">{arr(risks).slice(0,4).map((x:any,i:number)=><li key={i}>• {typeof x==='string'?x:fmtObj(x)}</li>)}</ul></div>}</div>}
function TargetUserTable({rows}:any){return <Table title="目标用户 / 需求入口" cols={['用户分群','痛点','付费触发','可触达入口','证据强度']} rows={rows.map((r:any)=>[r.segment,r.pain,r.payment_trigger||r.trigger,r.entry||r.evidence,r.confidence])}/>}
function CompetitorTable({rows,fallback}:any){
 const [sort,setSort]=useState('threat')
 const [detail,setDetail]=useState<any|null>(null)
 const data=(rows.length?rows:fallback.map((c:any)=>({name:c.name||c.domain,domain:c.domain,url:c.url,positioning:c.notes,pricing:c.pricing_url,maturity:'-',strengths:['待分析'],weaknesses:['待分析'],direct_competition:'-',similarity:'-',threat:'-',our_wedge:'待补证',evidence:c.notes,confidence:'low'}))).map((r:any)=>normalizeCompetitor(r))
 const sorted=[...data].sort((a:any,b:any)=>rankCompetitor(b,sort)-rankCompetitor(a,sort))
 return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-white">竞争对手分析</h3><p className="mt-1 text-xs text-slate-500">表格只放关键判断；点击公司名称看完整 LLM 分析。</p></div><select className="rounded-lg border border-slate-700 bg-slate-950 px-2 py-1 text-xs text-slate-200" value={sort} onChange={e=>setSort(e.target.value)}><option value="threat">威胁排序</option><option value="similarity">相似度排序</option><option value="maturity">成熟度排序</option><option value="direct">正面竞争排序</option><option value="confidence">置信度排序</option></select></div><div className="mt-3 overflow-hidden rounded-xl border border-slate-800"><table className="w-full table-fixed text-left text-xs"><colgroup><col className="w-[20%]"/><col className="w-[28%]"/><col className="w-[13%]"/><col className="w-[12%]"/><col className="w-[27%]"/></colgroup><thead className="bg-slate-950 text-slate-500"><tr><th className="px-3 py-2">公司</th><th className="px-3 py-2">定位</th><th className="px-3 py-2">正面竞争</th><th className="px-3 py-2">威胁</th><th className="px-3 py-2">我们的切入点</th></tr></thead><tbody>{sorted.length?sorted.map((r:any,i:number)=><tr key={`${r.domain}-${i}`} className="border-t border-slate-800 align-top"><td className="px-3 py-3"><button className="max-w-full break-words text-left font-semibold text-blue-300 hover:text-blue-200" title={r.domain||r.name} onClick={()=>setDetail(r)}>{r.name||r.domain||'-'}</button>{r.domain&&<div className="mt-1 break-words text-[11px] text-slate-500">{r.domain}</div>}</td><td className="px-3 py-3"><p className="break-words leading-5 text-slate-300">{r.positioning||'-'}</p></td><td className="px-3 py-3"><Badge value={r.direct_competition}/></td><td className="px-3 py-3"><Badge value={r.threat}/></td><td className="px-3 py-3"><p className="break-words leading-5 text-slate-300">{r.our_wedge||'-'}</p></td></tr>):<tr><td colSpan={5} className="px-3 py-4 text-center text-slate-500">暂无竞品分析，需要继续抓取证据。</td></tr>}</tbody></table></div>{detail&&<CompetitorDetail competitor={detail} onClose={()=>setDetail(null)}/>}</section>
}
function normalizeCompetitor(r:any){return {...r,strengths:arr(r.strengths||r.strength),weaknesses:arr(r.weaknesses||r.weakness),core_features:arr(r.core_features),our_wedge:r.our_wedge||r.wedge, direct_competition:r.direct_competition||'-'}}
function rankValue(x:any){const v=String(x||'').toLowerCase(); if(['critical','direct','high'].includes(v)) return 4; if(['medium','indirect'].includes(v)) return 3; if(['low'].includes(v)) return 2; if(['none','no','-'].includes(v)) return 1; return 0}
function rankCompetitor(r:any,sort:string){if(sort==='direct') return rankValue(r.direct_competition); return rankValue(r[sort])}
function Badge({value}:{value:any}){const v=String(value||'-'); const tone=rankValue(v)>=4?'bg-rose-500/10 text-rose-200':rankValue(v)>=3?'bg-amber-500/10 text-amber-200':rankValue(v)>=2?'bg-blue-500/10 text-blue-200':'bg-slate-800 text-slate-300'; return <span className={`whitespace-nowrap rounded-lg px-2 py-1 text-[11px] ${tone}`}>{v}</span>}
function CompetitorDetail({competitor,onClose}:any){return <div className="fixed inset-0 z-[60]"><button className="absolute inset-0 bg-black/70" onClick={onClose}/><aside className="absolute right-0 top-0 h-full w-full max-w-4xl overflow-y-auto border-l border-slate-800 bg-slate-950 p-5 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-3"><div><div className="text-xs uppercase tracking-[0.25em] text-blue-300">Competitor Detail</div><h3 className="mt-1 text-2xl font-bold text-white">{competitor.name||competitor.domain}</h3><p className="mt-1 text-sm text-slate-400">{competitor.domain} · 威胁 {competitor.threat} · 相似度 {competitor.similarity} · 正面竞争 {competitor.direct_competition}</p></div><button className="btn-secondary" onClick={onClose}>关闭</button></div><div className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Info title="产品定位" text={competitor.positioning}/><Info title="目标客户" text={competitor.target_customer}/><Info title="定价 / 收费信号" text={competitor.pricing}/></div><Info title="核心功能" text={arr(competitor.core_features).join('\n')}/><div className="grid gap-4 md:grid-cols-2"><List title="做得好的地方" rows={arr(competitor.strengths)}/><List title="弱点 / 缺口" rows={arr(competitor.weaknesses)}/></div><div className="grid gap-4 md:grid-cols-2"><Info title="护城河 / 壁垒" text={competitor.moat}/><Info title="主要获客方式" text={competitor.acquisition}/></div><div className="grid gap-4 md:grid-cols-2"><Info title="用户为什么选择它" text={competitor.why_users_choose_them}/><Info title="用户为什么离开 / 不满意" text={competitor.why_users_leave}/></div><Info title="我们的切入点 / 绕开方式" text={competitor.our_wedge}/><Info title="证据摘要" text={competitor.evidence}/><div className="flex flex-wrap gap-2 text-xs"><Badge value={`maturity: ${competitor.maturity}`}/><Badge value={`threat: ${competitor.threat}`}/><Badge value={`similarity: ${competitor.similarity}`}/><Badge value={`confidence: ${competitor.confidence}`}/></div></div></aside></div>}
function AcquisitionTable({rows}:any){return <Table title="获客方式" cols={['渠道','入口','验证动作','成本','置信']} rows={rows.map((r:any)=>[r.channel,r.entry,r.test_action||r.evidence,r.cost,r.confidence])}/>} 
function EvidencePlanTable({rows}:any){return <Table title="证据抓取 / 验证计划" cols={['待验证假设','当前证据','验证方法','成功信号','优先级']} rows={rows.map((r:any)=>[r.hypothesis||r.area,r.current_evidence||r.evidence,r.method,r.success_signal,r.priority])}/>}
function Table({title,cols,rows}:{title:string;cols:string[];rows:any[][]}){return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3><div className="mt-3 overflow-hidden rounded-xl border border-slate-800"><table className="w-full table-fixed text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr>{cols.map(c=><th key={c} className="px-3 py-2">{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t border-slate-800 align-top">{r.map((x,j)=><td key={j} className="whitespace-pre-wrap break-words px-3 py-2 leading-5 text-slate-300">{x||'-'}</td>)}</tr>):<tr><td colSpan={cols.length} className="px-3 py-4 text-center text-slate-500">暂无，需要继续抓取证据。</td></tr>}</tbody></table></div></section>}
function Select({value,setValue,options}:any){return <select className="input" value={value} onChange={e=>setValue(e.target.value)}>{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>}
function arr(x:any){return Array.isArray(x)?x.filter(Boolean):x?[x]:[]}
function fmtObj(x:any){if(!x) return ''; if(typeof x==='string') return x; return Object.entries(x).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join('；'):v}`).join('\n')}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-slate-950/80 p-2"><div className="text-slate-500">{label}</div><b className="text-slate-100">{value??'-'}</b></div>}
function Info({title,text}:{title:string;text?:string}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{text||'暂无'}</p></div>}
function List({title,rows}:{title:string;rows:any[]}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="font-bold text-white">{title}</h3>{rows.length?<ul className="mt-2 space-y-2 text-sm text-slate-300">{rows.map((x,i)=><li key={i} className="whitespace-pre-wrap rounded-xl bg-slate-950 p-2">{typeof x==='string'?x:fmtObj(x)}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">暂无。</p>}</div>}
function statusLabel(x:string){const m:any={not_started:'未开始',needs_prd:'待上传 PRD',prd_ready:'待产品分析',analysis_continue:'继续推进',analysis_need_evidence:'需补证',analysis_adjust_prd:'需改 PRD',analysis_pause:'暂停'}; return m[x]||x}
function riskRank(x:string){return {critical:4,high:3,medium:2,low:1,unknown:0}[x as string]||0}
function riskClass(x:string){return `rounded-lg px-2 py-1 text-xs ${x==='critical'||x==='high'?'bg-rose-500/10 text-rose-200':x==='medium'?'bg-amber-500/10 text-amber-200':x==='low'?'bg-emerald-500/10 text-emerald-200':'bg-slate-800 text-slate-300'}`}
function formatBytes(size:number){if(!size) return '0 B'; const units=['B','KB','MB','GB']; let n=size; let i=0; while(n>=1024&&i<units.length-1){n/=1024; i++} return `${n.toFixed(n>=10||i===0?0:1)} ${units[i]}`}
