'use client'
import {useMemo, useState} from 'react'
import {api} from '../lib/api'
const groups:any={Search:['SEARXNG_URL','SEARXNG_ENGINES','SEARXNG_API_TOKEN'],Automation:['AUTO_RUN_ENABLED','AUTO_RUN_INTERVAL_MINUTES','AUTO_RUN_LIMIT'],Quality:['MIN_ACTION_SCORE','REQUIRE_SOCIAL_FOR_ACTION','COLLECT_SOCIAL_EVIDENCE','BLOCKED_TERMS'],Integrations:['BRAVE_API_KEY','TAVILY_API_KEY','LLM_PROVIDER','LLM_API_KEY']}
export function SettingsForm({rows}:{rows:any[]}){
 const [items,setItems]=useState(rows); const [msg,setMsg]=useState(''); const [testing,setTesting]=useState(false)
 const byKey=useMemo(()=>Object.fromEntries(items.map((x:any)=>[x.key,x])),[items])
 function update(key:string, patch:any){setItems(items.map((x:any)=>x.key===key?{...x,...patch}:x))}
 async function save(key:string){const s=items.find((x:any)=>x.key===key); await api('/api/settings',{method:'POST',body:JSON.stringify(s)}); setMsg(`Saved ${key}`)}
 async function saveGroup(keys:string[]){for(const k of keys){const s=items.find((x:any)=>x.key===k); if(s) await api('/api/settings',{method:'POST',body:JSON.stringify(s)})} setMsg('Saved group')}
 async function test(){setTesting(true);setMsg('Testing SearXNG...'); try{const r=await api<any>('/api/settings/test-search',{method:'POST'}); setMsg(r.ok?`✅ SearXNG OK: ${r.result_count} results, ${r.elapsed_ms}ms`:`❌ SearXNG failed: ${r.error}`)}catch(e:any){setMsg(`❌ ${e.message}`)} finally{setTesting(false)}}
 return <div className="space-y-6"><div className="flex flex-wrap items-center gap-3"><button className="btn" disabled={testing} onClick={test}>{testing?'Testing...':'Test SearXNG'}</button>{msg&&<span className="rounded-xl bg-slate-950 px-3 py-2 text-sm text-slate-200">{msg}</span>}</div>{Object.entries(groups).map(([name,keys]:any)=><section className="panel" key={name}><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">{name}</h2><p className="text-sm text-slate-500">{name==='Search'?'搜索入口和可用引擎':name==='Automation'?'后台自动运行策略':name==='Quality'?'Action 门槛和噪音控制':'外部 API / LLM 预留配置'}</p></div><button className="btn-secondary" onClick={()=>saveGroup(keys)}>Save group</button></div><div className="space-y-3">{keys.map((key:string)=>{const s=byKey[key]||{key,value:'',secret:false}; const bool=['AUTO_RUN_ENABLED','REQUIRE_SOCIAL_FOR_ACTION','COLLECT_SOCIAL_EVIDENCE'].includes(key); return <div key={key} className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-950/60 p-4 md:grid-cols-12"><div className="md:col-span-3"><div className="font-semibold">{key}</div><div className="text-xs text-slate-500">{s.secret?'secret':'plain'} · {s.updated_at?new Date(s.updated_at).toLocaleString():''}</div></div><div className="md:col-span-7">{bool?<select className="input w-full" value={s.value||'false'} onChange={e=>update(key,{value:e.target.value})}><option value="true">true</option><option value="false">false</option></select>:<input className="input w-full" type={s.secret?'password':'text'} value={s.value||''} onChange={e=>update(key,{value:e.target.value})}/>}</div><label className="flex items-center gap-2 text-xs text-slate-400 md:col-span-1"><input type="checkbox" checked={!!s.secret} onChange={e=>update(key,{secret:e.target.checked})}/> secret</label><button className="btn md:col-span-1" onClick={()=>save(key)}>Save</button></div>})}</div></section>)}</div>
}
