import {api} from '../lib/api'
import {StatCard} from '../components/StatCard'
import {OpportunityCardView} from '../components/OpportunityCard'
import {RunStatus} from '../components/RunStatus'
import {I18nText} from '../components/I18nText'
export default async function Page(){
 const health=await api<any>('/api/health'); const cards=await api<any[]>('/api/cards'); const runs=await api<any[]>('/api/runs'); const auto=await api<any>('/api/auto/status'); const settings=await api<any[]>('/api/settings')
 const counts={Action:cards.filter(c=>c.verdict==='Action').length,Watch:cards.filter(c=>c.verdict==='Watch').length,Reject:cards.filter(c=>c.verdict==='Reject').length}
 const ready = settings.find(s=>s.key==='SEARXNG_ENGINES')?.value && settings.find(s=>s.key==='AUTO_RUN_ENABLED')?.value==='true'
 const top=cards.filter(c=>c.verdict!=='Reject').slice(0,4)
 return <div className="space-y-8"><section className="rounded-3xl border border-blue-500/30 bg-gradient-to-br from-blue-950/80 via-slate-950 to-slate-950 p-8 shadow-2xl"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[0.3em] text-blue-300">Demand Hunter</p><h1 className="mt-3 text-4xl font-black text-white"><I18nText zh='机会发现操作台' en='Opportunity Discovery Console'/></h1><p className="mt-3 max-w-2xl text-slate-300"><I18nText zh='自动组合词根、跑 SERP、识别竞品缺口，并把低质量噪音挡在 Action 之外。当前目标：宁缺毋滥，只把可验证机会推进。' en='Combine roots, run SERP, identify competitor gaps, and keep low-quality noise out of Action. Current goal: fewer cards, higher confidence.'/></p></div><div className={ready?'badge badge-action':'badge badge-watch'}>{ready?<I18nText zh='系统就绪' en='System Ready'/>:<I18nText zh='需要配置' en='Needs Setup'/>}</div></div></section><div className="grid gap-4 md:grid-cols-5"><StatCard label="Keywords" value={health.keywords} tone="blue"/><StatCard label="Cards" value={health.cards}/><StatCard label="Action" value={counts.Action} tone="green"/><StatCard label="Watch" value={counts.Watch} tone="amber"/><StatCard label="Reject" value={counts.Reject} tone="rose"/></div><RunStatus auto={auto}/><section className="grid gap-6 lg:grid-cols-3"><div className="panel lg:col-span-2"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold"><I18nText zh='当前最值得看的机会' en='Current top opportunities'/></h2><a href="/cards" className="btn-secondary"><I18nText zh='查看全部' en='View all'/></a></div><div className="grid gap-4 md:grid-cols-2">{top.length?top.map(c=><OpportunityCardView key={c.id} card={c} compact/>):<div className="rounded-2xl border border-slate-800 bg-slate-950 p-6 text-slate-400"><I18nText zh='还没有 Action/Watch 卡片。先运行一次自动找词。' en='No Action/Watch cards yet. Run automatic discovery first.'/></div>}</div></div><aside className="panel"><h2 className="text-xl font-bold"><I18nText zh='下一步' en='Next steps'/></h2><ol className="mt-4 space-y-3 text-sm text-slate-300"><li><b>1. Settings</b><br/>确认 SearXNG Test 为 OK，调整自动运行数量。</li><li><b>2. Run</b><br/>点击 Force Auto Tick 或等待后台自动跑。</li><li><b>3. Review</b><br/>对卡片标 Action/Watch/Reject/Block，系统会调整词根。</li><li><b>4. Expand</b><br/>在 Root Library 加行业/痛点词根。</li></ol></aside></section><section className="panel"><h2 className="mb-3 text-xl font-bold"><I18nText zh='最近运行' en='Recent runs'/></h2>{runs.slice(0,5).map(r=><div key={r.id} className="flex items-center justify-between border-t border-slate-800 py-3 text-sm"><span>#{r.id} · {r.kind}</span><span className={r.status==='ok'?'text-emerald-300':r.status==='running'?'text-blue-300':'text-rose-300'}>{r.status}</span><span className="text-slate-400">{JSON.stringify(r.summary)}</span></div>)}</section></div>
}
